[package]
name = "rust_noise"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_noise"
crate-type = ["cdylib"]

[dependencies]
euclid = "0.22"
noise = "0.9.0"
pyo3 = { version = "0.25.0", features = ["extension-module"] }
rand = "0.9.1"

