# STAGES
stages:
  - test
  - release

# Run tests
run_tests:
  image: python:3.10
  stage: test

  before_script:
    # Install missing deps
    - apt-get update
    - apt-get install -y libgl1-mesa-dev

    # Install deps launch
    - pip install -r requirements.txt
    - parentdir="$(dirname `pwd`)"
    - export PYTHONPATH=$parentdir:$PYTHONPATH

  script:
    - python -m unittest discover ./test

# Release
release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
