[package]
name = "rust_regex"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_regex"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.0", features = ["extension-module"] }
rayon = "1.7.0"
regex = "1.9.3"

