on:
  push:
    tags:
      - '0.*'
      - '1.*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1